# strategy/reason_codes.py

LONG_ENTRY = (
    "HTF_BULLISH | HH_HL | OBV_UP | LIQUIDITY_SWEPT | OB_MITIGATION"
)

SHORT_ENTRY = (
    "HTF_BEARISH | LL_LH | OBV_DOWN | LIQUIDITY_SWEPT | OB_MITIGATION"
)
